export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_FULFILLED = 'ADD_PRODUCT_FULFILLED'
export const PRODUCTS_REJECTED = 'PRODUCTS_REJECTED'